[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remapping = '[@chainlink/contracts/src/v0.8/shared/interfaces/AggregatorV3Interface.sol]'
ffi = true
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]